// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAIJyChhlentJtmJzp-oJZj8LOZDdCgw',
    appId: '1:249444010812:web:23430515d81fabb79d2c39',
    messagingSenderId: '249444010812',
    projectId: 'fooddelivery-52a1e',
    authDomain: 'fooddelivery-52a1e.firebaseapp.com',
    storageBucket: 'fooddelivery-52a1e.appspot.com',
    measurementId: 'G-PF3H3CXLP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPmEUrXlm97Tryd6HPihBLVcgoF__QdI',
    appId: '1:249444010812:android:1f67720e570187d39d2c39',
    messagingSenderId: '249444010812',
    projectId: 'fooddelivery-52a1e',
    storageBucket: 'fooddelivery-52a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6redGvozug9Z8tgQsuxyUnCLJ8KiaW5s',
    appId: '1:249444010812:ios:9cdb1abf1b9670f09d2c39',
    messagingSenderId: '249444010812',
    projectId: 'fooddelivery-52a1e',
    storageBucket: 'fooddelivery-52a1e.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6redGvozug9Z8tgQsuxyUnCLJ8KiaW5s',
    appId: '1:249444010812:ios:9cdb1abf1b9670f09d2c39',
    messagingSenderId: '249444010812',
    projectId: 'fooddelivery-52a1e',
    storageBucket: 'fooddelivery-52a1e.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvAIJyChhlentJtmJzp-oJZj8LOZDdCgw',
    appId: '1:249444010812:web:0e2dc2ef5944044d9d2c39',
    messagingSenderId: '249444010812',
    projectId: 'fooddelivery-52a1e',
    authDomain: 'fooddelivery-52a1e.firebaseapp.com',
    storageBucket: 'fooddelivery-52a1e.appspot.com',
    measurementId: 'G-M4GNQ54ED7',
  );
}